### ISSUE TITLE
No module named magic

### ISSUE THREAD

**Issue by FidiasR** [daddyfix/cellular_modem_communicator#1]
Hi,
When I run the script I have an error when installing the magic module.
I could not find the right one.

Installing magic module...
Collecting magic
  Could not find a version that satisfies the requirement magic (from versions: )
No matching distribution found for magic
Traceback (most recent call last):
  File "cellular_communicator.py", line 53, in <module>
    import magic
ImportError: No module named magic

Thanks,

**Comment by daddyfix** [comment]
I have written new and better code. I will contact you once I get back home.

If I remember correctly, I had the same issues with the magic portion. I
think I changed part of the script.

I'll get back to you soon

**Comment by daddyfix** [comment]
The new code I use is here ([https://github.com/daddyfix/lte-send.py](https://github.com/daddyfix/lte-send.py)).

But I noticed I am still using the module 'magic'.

If using Python <2.7.9 (default, Sep 26 2018, 05:58:52).... try

sudo apt-get update; sudo apt-get install python-magic

If you are using Python 3+ then try install magic like

sudo update; sudo apt-get install python3-magic

**Comment by FidiasR** [comment]
Thanks very much, i will test it this weekend.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
